# Generated by Django 6.0 on 2025-12-15 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_saveditem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLACED", "Placed"),
                    ("ASSIGNED", "Assigned"),
                    ("OUT", "Out for delivery"),
                    ("DELIVERED", "Delivered"),
                ],
                default="PLACED",
                max_length=20,
            ),
        ),
    ]
